/**
 * Constants and enums for Decor8 AI SDK.
 */

// Room types supported by the API
const ROOM_TYPES = [
    "LIVINGROOM", "KITCHEN", "DININGROOM", "BEDROOM", "BATHROOM",
    "KIDSROOM", "FAMILYROOM", "READINGNOOK", "SUNROOM", "WALKINCLOSET",
    "MUDROOM", "TOYROOM", "OFFICE", "FOYER", "POWDERROOM", "LAUNDRYROOM",
    "GYM", "BASEMENT", "GARAGE", "BALCONY", "CAFE", "HOMEBAR",
    "STUDY_ROOM", "FRONT_PORCH", "BACK_PORCH", "BACK_PATIO", "OPENPLAN",
    "BOARDROOM", "MEETINGROOM", "OPENWORKSPACE", "PRIVATEOFFICE"
];

// Design styles supported by the API
const DESIGN_STYLES = [
    "MINIMALIST", "SCANDINAVIAN", "INDUSTRIAL", "BOHO", "TRADITIONAL",
    "ARTDECO", "MIDCENTURYMODERN", "COASTAL", "TROPICAL", "ECLECTIC",
    "CONTEMPORARY", "FRENCHCOUNTRY", "RUSTIC", "SHABBYCHIC", "VINTAGE",
    "COUNTRY", "MODERN", "ASIAN_ZEN", "HOLLYWOODREGENCY", "BAUHAUS",
    "MEDITERRANEAN", "FARMHOUSE", "VICTORIAN", "GOTHIC", "MOROCCAN",
    "SOUTHWESTERN", "TRANSITIONAL", "MAXIMALIST", "ARABIC", "JAPANDI",
    "RETROFUTURISM", "ARTNOUVEAU", "URBANMODERN", "WABI_SABI",
    "GRANDMILLENNIAL", "COASTALGRANDMOTHER", "NEWTRADITIONAL", "COTTAGECORE",
    "LUXEMODERN", "HIGH_TECH", "ORGANICMODERN", "TUSCAN", "CABIN",
    "DESERTMODERN", "GLOBAL", "INDUSTRIALCHIC", "MODERNFARMHOUSE",
    "EUROPEANCLASSIC", "NEOTRADITIONAL", "WARMMINIMALIST"
];

// Color schemes (predefined palettes)
const COLOR_SCHEMES = Array.from({ length: 21 }, (_, i) => `COLOR_SCHEME_${i}`);

// Specialty decor options (seasonal/thematic)
const SPECIALITY_DECORS = Array.from({ length: 8 }, (_, i) => `SPECIALITY_DECOR_${i}`);

// Sky types for sky replacement
const SKY_TYPES = ["DAY", "DUSK", "NIGHT"];

// Yard types for landscaping
const YARD_TYPES = ["FRONT_YARD", "BACKYARD", "SIDE_YARD"];

// Garden styles for landscaping
const GARDEN_STYLES = [
    "JAPANESE_ZEN", "MEDITERRANEAN", "ENGLISH_COTTAGE", "TROPICAL", "DESERT",
    "MODERN_MINIMALIST", "FRENCH_FORMAL", "COASTAL", "WOODLAND", "PRAIRIE",
    "ROCK_GARDEN", "WATER_GARDEN", "HERB_GARDEN", "CUTTING_GARDEN", "POLLINATOR",
    "XERISCAPE", "EDIBLE_LANDSCAPE", "MOON_GARDEN", "RAIN_GARDEN", "SENSORY",
    "NATIVE_PLANT", "COTTAGE_STYLE", "FORMAL_PARTERRE", "NATURALISTIC",
    "CONTEMPORARY", "ASIAN_FUSION", "RUSTIC_FARMHOUSE", "URBAN_MODERN",
    "SUSTAINABLE", "WILDLIFE_HABITAT", "FOUR_SEASON"
];

// Render types for sketch to 3D
const RENDER_TYPES = ["PERSPECTIVE", "ISOMETRIC"];

module.exports = {
    ROOM_TYPES,
    DESIGN_STYLES,
    COLOR_SCHEMES,
    SPECIALITY_DECORS,
    SKY_TYPES,
    YARD_TYPES,
    GARDEN_STYLES,
    RENDER_TYPES
};
